* Config/Preamble :noexport:
** LaTeX Config
#+BEGIN_SRC emacs-lisp :exports none :results none :eval always
  (setq org-latex-logfiles-extensions (quote ("lof" "lot" "tex~" "aux" "idx" "log" "out" "toc" "nav" "snm" "vrb" "dvi" "fdb_latexmk" "blg" "brf" "fls" "entoc" "ps" "spl" "bbl" "xmpi" "run.xml" "bcf")))
  (setq org-latex-pdf-process (list
   "latexmk -pdflatex='lualatex -shell-escape -interaction nonstopmode' -pdf -f  %f"))
  (add-to-list 'org-latex-classes
               '("altacv" "\\documentclass[10pt,a4paper,ragged2e,withhyper]{altacv}

  % Change the page layout if you need to
  \\geometry{left=1.0cm,right=1.0cm,top=1.5cm,bottom=1.5cm,columnsep=1.2cm}
  \\sloppy

  % Use roboto and lato for fonts
  \\renewcommand{\\familydefault}{\\sfdefault}

  % Change the colours if you want to
  \\definecolor{SlateGrey}{HTML}{2E2E2E}
  \\definecolor{LightGrey}{HTML}{666666}
  \\definecolor{DarkPastelRed}{HTML}{450808}
  \\definecolor{PastelRed}{HTML}{8F0D0D}
  \\definecolor{GoldenEarth}{HTML}{E7D192}
  \\colorlet{name}{black}
  \\colorlet{tagline}{PastelRed}
  \\colorlet{heading}{DarkPastelRed}
  \\colorlet{headingrule}{GoldenEarth}
  \\colorlet{subheading}{PastelRed}
  \\colorlet{accent}{PastelRed}
  \\colorlet{emphasis}{SlateGrey}
  \\colorlet{body}{LightGrey}

  % Change some fonts, if necessary
  \\renewcommand{\\namefont}{\\Huge\\rmfamily\\bfseries}
  \\renewcommand{\\personalinfofont}{\\footnotesize}
  \\renewcommand{\\cvsectionfont}{\\LARGE\\rmfamily\\bfseries}
  \\renewcommand{\\cvsubsectionfont}{\\large\\bfseries}

  % Change the bullets for itemize and rating marker
  % for \cvskill if you want to
  \\renewcommand{\\itemmarker}{{\\small\\textbullet}}
  \\renewcommand{\\ratingmarker}{\\faCircle}
  "

                 ("\\cvsection{%s}" . "\\cvsection*{%s}")
                 ("\\cvevent{%s}" . "\\cvevent*{%s}")))
  (setq org-latex-packages-alist 'nil)
  (setq org-latex-default-packages-alist
        '(("rm" "roboto"  t)
          ("defaultsans" "lato" t)
          ("" "paracol" t)
          ))
#+END_SRC
#+LATEX_CLASS: altacv
#+LATEX_HEADER: \columnratio{0.55} % Set the left/right column width ratio to 6:4.
#+LATEX_HEADER: \usepackage[bottom]{footmisc}
*** Bibliography
# #+LATEX_HEADER: \usepackage[backend=biber,style=apa,sorting=none,natbib=true]{biblatex}
# #+LATEX_HEADER: \usepackage[style=trad-abbrv,sorting=none,sortcites=true,doi=false,url=true,giveninits=true,hyperref]{biblatex}
#+LATEX_HEADER: \usepackage[backend=biber,style=apa6,sorting=ydnt]{biblatex}
#+LATEX_HEADER: \defbibheading{pubtype}{\cvsubsection{#1}}
#+LATEX_HEADER: \renewcommand{\bibsetup}{\vspace*{-\baselineskip}}
#+LATEX_HEADER: \AtEveryBibitem{\makebox[\bibhang][l]{\itemmarker}}
#+LATEX_HEADER: \setlength{\bibitemsep}{0.25\baselineskip}
#+LATEX_HEADER: \setlength{\bibhang}{1.25em}
#+LATEX_HEADER: \addbibresource{davis.bib}
** Exporter Settings
#+AUTHOR: Davis Schenkenberger
#+EXPORT_FILE_NAME: ./schenkenberger-resume.pdf
#+OPTIONS: toc:nil title:nil H:1
** Macros 
#+MACRO: cvevent \cvevent{$1}{$2}{$3}{$4}
#+MACRO: cvachievement \cvachievement{$1}{$2}{$3}{$4}
#+MACRO: cvtag \cvtag{$1}
#+MACRO: divider \divider
#+MACRO: par-div \par\divider
#+MACRO: new-page \newpage
* CV Header :ignore:
** Photo & Tagline :ignore:
#+begin_export latex
\name{Davis Schenkenberger}
\photoR{2.8cm}{picture.jpeg}
\tagline{Software Developer}
#+end_export

** Personal Info :ignore:
#+begin_export latex
\personalinfo{
  \email{davisschenk@gmail.com}
  \email{davis13@colostate.edu}
  \phone{(970) 590-1219}
  \github{davisschenk}
  \linkedin{davis-schenkenberger-686a02157}
}
\makecvheader
#+end_export

* CV Column 1 :ignore:
#+LATEX: \begin{paracol}{2}
** Personal Statement :ignore:noexport:
#+begin_export latex
\begin{quote}
 ``Student studying Computer Science at Colorado Science with an interest in UAV technology and embedded systems. Experience with open-source contribution and working with a team of developers in academic, work and hobby settings.''
\end{quote}
#+end_export
** Personal Statement Esri :ignore:
#+begin_export latex
\begin{quote}
 ``Student studying Computer Science with a minor in Geospatial Information Sciences at Colorado Science with an interest in UAV technology and Geospatial Analysis. Experience with open-source contribution and working with a team of developers in academic, work and hobby settings.''
\end{quote}
#+end_export
** Experience
*** UAV Pilot :ignore:
{{{cvevent(Drone Technician and UAV Pilot, Colorado State University,May 2022 -- Present, Fort Collins\, Colorado)}}}
Helped with various projects ranging from agricultural research to tracking methane emissions at an abandoned coal mine. Automated various workflows helping to reduce the amount of manual labor and time spent sorting and processing data. Planned, piloted and maintained safety in numerous technical flight operations.

\vspace{1em}
{{{cvtag(Pix4D)}}}
{{{cvtag(ArcGIS Pro)}}}
{{{cvtag(QGis)}}}
{{{cvtag(Wingtra One Gen II)}}}

{{{cvtag(Phantom 4 RTK)}}}

{{{divider}}}

*** Drone Technician :ignore:
{{{cvevent(Drone Technician, Colorado State University,Jan 2021 -- May 2022, Fort Collins\, Colorado)}}}
Lead a team of students to integrate a highend AHRS sensor with open source flight control software Ardupilot running on a Pixhawk 4.

\vspace{1em}
{{{cvtag(C++)}}}
{{{cvtag(Open Source Development)}}}
{{{cvtag(Drone Hardware)}}}

{{{cvtag(Ardupilot)}}}
{{{cvtag(PixHawk4)}}}

{{{divider}}}

*** Amazon :ignore:
{{{cvevent(Fulfillment/Sortation Associate, Nov 2020 -- Jan 2021 / Jun 2021 -- Sep 2021, Thorton\, Colorado)}}}
# At Amazon I worked on a large team to help sort merchandise and packages to allow customers to receive orders in a timely matter.

{{{divider}}}
*** Head Lifeguard :ignore:
{{{cvevent(Head Lifeguard, YMCA, Apr 2020 -- Aug 2020, Johnstown\, Colorado)}}}
# Worked to maintain patron well-being while managing a team of lifeguards and being responsible for maintaining the facility.

{{{divider}}}
*** Carbon Valley Recreation Center :ignore:
{{{cvevent(Lifeguard \& Swim Instructor, Carbon Valley Recreation Center, Jul 2018 -- Mar 2020, Frederick\, Colorado)}}}

{{{divider}}}

*** New Page :ignore:
{{{new-page}}}

** Projects
*** Ardupilot Lord Integration :ignore:
{{{cvevent(Ardupilot Lord Integration, Colorado State University Drone Center, Jun 2021 -- Present, Fort Collins\, Colorado)}}}
- Integrating a LORD 3DM-CX5-45 with Ardupilot
- Extensive testing using various flight platforms
- Designing and building a quadcopter
- \faGithub [[https://github.com/ArduPilot/ardupilot/pull/18837][Lord Microstrain Integration PR]]

\vspace{1em}
{{{cvtag(Embedded Technology)}}}
{{{cvtag(Ardupilot)}}}

{{{cvtag(Estimation Filter)}}}
{{{cvtag(Serial Communication)}}}

{{{cvtag(Integration Testing)}}}

*** Raspberry PI Leds :ignore:
{{{par-div}}}
{{{cvevent(Raspberry PI Leds, Colorado State University, Jun 2021 -- Present, Fort Collins\, Colorado)}}}
- Custom application to run animations on a WS2812b LED strip from a Raspberry PI
- LEDs are controlled using a REST API written in Rust running on the RPI
- Frontend written in Flutter/Dart so it can be used as a mobile app or website
- Custom PCB designed using KiCad
- \faGithub [[https://github.com/davisschenk/rasp_leds][davisschenk/rasp-leds]] 
- \faGithub [[https://github.com/davisschenk/rasp-leds-v2][davisschenk/rasp-leds-v2]]
*** Project Euler :ignore:
{{{par-div}}}
{{{cvevent(Project Euler, Colorado State University, Sep 2020 -- Present, Fort Collins\, Colorado)}}}
- Project Euler solutions written in both Python and Rust
- Custom framework to test, execute and benchmark solutions in Python
- \faGithub [[https://github.com/davisschenk/project-euler-python][davisschenk/project-euler-python]]
- \faGithub [[https://github.com/davisschenk/project-euler-rust][davisschenk/project-euler-rust]]

{{{cvtag(Python)}}}
{{{cvtag(Rust)}}}
{{{cvtag(Project Euler)}}}
*** Coal Basin Mine Emissions :ignore:
{{{par-div}}}
{{{cvevent(Coal Basin Methane Emissions Project, Colorado State University, July 2020, Fort Collins\, Colorado)}}}
I spent a week living in Coal Basin assisting a professor and another research assistant locate methane leaks, each day we would hike a few miles into the basin where we would collect quantitative data on the known leaks and try and find other locations where methane could be escaping the mine. During this time I collected data for building models using a Phantom 4 RTK and we attempted to use an Autel Evo 640t to locate new leaks using the thermal camera.

* CV Column 2 :ignore:
# Switch to the right column - will automatically move to the next page.
#+begin_export latex
\switchcolumn
#+end_export
** Skills
{{{cvtag(Python)}}}
{{{cvtag(Rust)}}}
{{{cvtag(C/C++)}}}
{{{cvtag(Java)}}}

{{{cvtag(Flutter \& Dart)}}}

{{{divider}}}

{{{cvtag(Docker)}}}
{{{cvtag(KiCad/PCB Design)}}}
{{{cvtag(Selenium)}}}
{{{cvtag(Git/GitHub/Actions)}}}
{{{cvtag(Ardupilot)}}}
{{{cvtag(LaTeX)}}}
{{{cvtag(Org-mode)}}}

{{{divider}}}

{{{cvtag(ArcGIS)}}}
{{{cvtag(QGIS)}}}
{{{cvtag(Pix4D)}}}
{{{cvtag(Geopandas, Pandas \& Numpy)}}}
{{{cvtag(Google Earth Pro)}}}

** Education
{{{cvevent(Bachelors in Computer Science,Colorado State Univeristy,Aug 2020 -- May 2024,Fort Collins\, Colorado)}}}
** References
#+begin_export latex
\cvref{Christopher Robertson}{Colorado State University Drone Center}{\href{mailto:christopher.robertson@colostate.edu}{christopher.robertson@colostate.edu}}
#+end_export
** Publications
#+begin_export latex
\nocite{*}\printbibliography[title={\printinfo{\faBook}{Academic}}]
#+end_export
** Achievements
{{{cvachievement(\faCertificate, Part 107 Pilots License, FAA certified remote pilot)}}}

{{{divider}}}

* Back Matter :ignore:
#+begin_export latex
\end{paracol}
\end{document}
#+end_export
