* Config/Preamble :noexport:
** LaTeX Config
#+BEGIN_SRC emacs-lisp :exports none :results none :eval always
  (setq org-latex-logfiles-extensions (quote ("lof" "lot" "tex~" "aux" "idx" "log" "out" "toc" "nav" "snm" "vrb" "dvi" "fdb_latexmk" "blg" "brf" "fls" "entoc" "ps" "spl" "bbl" "xmpi" "run.xml" "bcf")))
  (add-to-list 'org-latex-classes
               '("altacv" "\\documentclass[10pt,a4paper,ragged2e,withhyper]{altacv}

  % Change the page layout if you need to
  \\geometry{left=1.25cm,right=1.25cm,top=1.5cm,bottom=1.5cm,columnsep=1.2cm}

  % Use roboto and lato for fonts
  \\renewcommand{\\familydefault}{\\sfdefault}

  % Change the colours if you want to
  \\definecolor{SlateGrey}{HTML}{2E2E2E}
  \\definecolor{LightGrey}{HTML}{666666}
  \\definecolor{DarkPastelRed}{HTML}{450808}
  \\definecolor{PastelRed}{HTML}{8F0D0D}
  \\definecolor{GoldenEarth}{HTML}{E7D192}
  \\colorlet{name}{black}
  \\colorlet{tagline}{PastelRed}
  \\colorlet{heading}{DarkPastelRed}
  \\colorlet{headingrule}{GoldenEarth}
  \\colorlet{subheading}{PastelRed}
  \\colorlet{accent}{PastelRed}
  \\colorlet{emphasis}{SlateGrey}
  \\colorlet{body}{LightGrey}

  % Change some fonts, if necessary
  \\renewcommand{\\namefont}{\\Huge\\rmfamily\\bfseries}
  \\renewcommand{\\personalinfofont}{\\footnotesize}
  \\renewcommand{\\cvsectionfont}{\\LARGE\\rmfamily\\bfseries}
  \\renewcommand{\\cvsubsectionfont}{\\large\\bfseries}

  % Change the bullets for itemize and rating marker
  % for \cvskill if you want to
  \\renewcommand{\\itemmarker}{{\\small\\textbullet}}
  \\renewcommand{\\ratingmarker}{\\faCircle}
  "

                 ("\\cvsection{%s}" . "\\cvsection*{%s}")
                 ("\\cvevent{%s}" . "\\cvevent*{%s}")))
  (setq org-latex-packages-alist 'nil)
  (setq org-latex-default-packages-alist
        '(("rm" "roboto"  t)
          ("defaultsans" "lato" t)
          ("" "paracol" t)
          ))
#+END_SRC
#+LATEX_CLASS: altacv
#+LATEX_HEADER: \columnratio{0.6} % Set the left/right column width ratio to 6:4.
#+LATEX_HEADER: \usepackage[bottom]{footmisc}
** Exporter Settings
#+AUTHOR: Davis Schenkenberger
#+EXPORT_FILE_NAME: ./schenkenberger-resume.pdf
#+OPTIONS: toc:nil title:nil H:1
** Macros
#+MACRO: cvevent \cvevent{$1}{$2}{$3}{$4}
#+MACRO: cvachievement \cvachievement{$1}{$2}{$3}{$4}
#+MACRO: cvtag \cvtag{$1}
#+MACRO: divider \divider
#+MACRO: par-div \par\divider
#+MACRO: new-page \newpage
* CV Header :ignore:
** Photo & Tagline :ignore:
#+begin_export latex
\name{Davis Schenkenberger}
\photoR{2.8cm}{picture.jpeg}
\tagline{Software Developer}
#+end_export

** Personal Info :ignore:
#+begin_export latex
\personalinfo{
  \email{davisschenk@gmail.com}
  \email{davis13@colostate.edu}
  \phone{(970) 590-1219}
  \github{davisschenk}
  \linkedin{davis-schenkenberger-686a02157}
}
\makecvheader
#+end_export

* CV Column 1 :ignore:
#+begin_export latex
\begin{paracol}{2}
#+end_export
** Personal Statement :ignore:
#+begin_export latex
\begin{quote}
 ``I am a student studying Computer Science at Colorado State Univeristy, I have passion for Software Development especially embedded systems and backend services. I have lots of experience working on open source projects and leading teams of developers to achieve a goal.''
 \end{quote}
#+end_export
** Experience
*** Drone Technician :ignore:
{{{cvevent(Drone Technician, Colorado State University,Jan 2021 -- Present, Fort Collins\, Colorado)}}}
As an employee of the CSU Drone Center I worked with a team of other students to help develop software that allows a high-end AHRS to be used with open source flight control software. This position initially began as an independent study, but after successfully creating a pitch and receiving funding turned into a payed position.

{{{cvtag(C++)}}}
{{{cvtag(Open Source Development)}}}
{{{cvtag(Drone Hardware)}}}
{{{cvtag(Ardupilot)}}}
*** Fulfillment Associate :ignore:
{{{cvevent(Fulfillment Associate, Amazon, Jun 2021 -- Sep 2021, Thorton\, Colorado)}}}

*** Sortation Associate :ignore:
{{{cvevent(Fulfillment Associate, Amazon, Jun 2021 -- Sep 2021, Thorton\, Colorado)}}}

*** Head Lifeguard :ignore:
{{{cvevent(Head Lifeguard, Amazon, Apr 2020 -- Aug 2020, Johnstown\, Colorado)}}}

*** Carbon Valley Recreation Center :ignore:
{{{cvevent(Lifeguard & Swim Instructor, Carbon Valley Recreation Center, Jul 2018 -- Mar 2020, Frederick\, Colorado)}}}

** Projects
*** Ardupilot Lord Integration :ignore:
{{{cvevent(Ardupilot Lord Integration, Colorado State University Drone Center, Jun 2021 -- Present, Fort Collins\, Colorado)}}}

\faGithub [[https://github.com/ArduPilot/ardupilot/pull/18837][Lord Microstrain Integration PR]]

{{{cvtag(Embedded Technology)}}}
{{{cvtag(Ardupilot)}}}
{{{cvtag(Estimation Filter)}}}
* CV Column 2 :ignore:
# Switch to the right column - will automatically move to the next page.
#+begin_export latex
\switchcolumn
#+end_export

** Skills
{{{cvtag(Python)}}}
{{{cvtag(Rust)}}}
{{{cvtag(C/C++)}}}
{{{cvtag(Java)}}}
{{{cvtag(Flutter & Dart)}}}
{{{divider}}}

{{{cvtag(Docker)}}}
{{{cvtag(KiCad/PCB Design)}}}
{{{cvtag(Selenium)}}}
{{{cvtag(Git/GitHub/Actions)}}}
{{{cvtag(Ardupilot)}}}
{{{cvtag(LaTeX)}}}
{{{cvtag(Org-mode)}}}

** Education
{{{cvevent(Bachelors in Computer Science, Colorado State Univeristy, Aug 2020 -- Present, Fort Collins\, Colorado)}}}
** References
#+begin_export latex
\cvref{Christopher Robertson}{Colorado State University Drone Center}{\href{mailto:christopher.robertson@colostate.edu}{christopher.robertson@colostate.edu}}
#+end_export
* Back Matter :ignore:
#+begin_export latex
\end{paracol}
\end{document}
#+end_export



